language: python
python:
#    - "2.6"
    - "2.7"
#    - "3.3"
#    - "pypy"

before_install:
     - git submodule update --init --recursive

install:
   - "git clone https://github.com/OpenTreeOfLife/peyotl.git && cd peyotl && pip install -r requirements.txt &&  python setup.py develop && cd .. "
   - pip install -r requirements.txt
   # Travis builder defaults don't play nicely with multiprocessing.Queue
   # - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"


before_script:
    - wget https://github.com/web2py/web2py/archive/R-2.4.4.zip
    - unzip R-2.4.4.zip
    - export API_BASE_DIR=`pwd`
    - cd web2py-R-2.4.4
    - cd applications
    # move the default welcome app out of the way
    - mv welcome welcome.back
    # make the root of this repo the default application
    - ln -sf $API_BASE_DIR welcome
    - cd ..
    - python web2py.py -i localhost --nogui --debug=0 -p 8000 -a 'supersekret' &> web2py.log &
    - sleep 3 # give the webserver time to startup
    - cat web2py.log
    - cd ..
    - git status -sbu

script:
    - true

after_script:
    - git status -sbu
    - cat web2py-*/web2py.log
    - ps auxw|grep python
    - sudo dmesg | tail -n50

notifications:
  irc:
    channels: "chat.freenode.net#opentreeoflife"
  email:
    on_success: change
    on_failure: always
env:

services:
#    - redis-server
